language: cpp
dist: bionic

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential linux-headers-$(uname -r) libgflags-dev wget git curl bc
  - export NUM_THREADS=4
  - export SCRIPTS=./travis

install:
  - sudo -E $SCRIPTS/install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

script: 
  - export PATH=/usr/bin:/usr/local/bin:$PATH
  - which cmake
  - cmake --version
  - $SCRIPTS/run.sh

notifications:
  email:
    on_success: false
    on_failure: always
