language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential cuda-toolkit-10-0 libgtest-dev cmake
  - export NUM_THREADS=4
  - export SCRIPTS=./travis

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

script: $SCRIPTS/run.sh

notifications:
  email:
    on_success: false
    on_failure: always
