language: cpp
dist: bionic

compiler:
  - gcc
  - clang

os:
  - linux
#  - osx

before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential linux-headers-$(uname -r) nvidia-cuda-toolkit libgflags-dev wget git curl bc
  - export NUM_THREADS=4
  - export SCRIPTS=./travis

install:
  - sudo -E $SCRIPTS/install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64

script: $SCRIPTS/run.sh

notifications:
  email:
    on_success: false
    on_failure: always
